### ISSUE TITLE
CDC_expert/TRIG_online plugin problems

### ISSUE THREAD

**Issue by sparksn** [JeffersonLab/sim-recon#207]
Has anyone else had problems recently with the CDC_expert and TRIG_online plugins?
I am testing them with run 3180, and CDC_expert crashes while TRIG_online gets stuck. 
These problems appear to be due to bugs introduced within the last week.

**Comment by sparksn** [comment]
TRIG_online hanging problem only occurs for multithreaded running.
CDC_expert crashes regardless of number of threads.

**Comment by eltonssmith** [comment]
I ran the TRIG_online plugin from my own branch, so it is not a direct comparison. Most of the changes from the trunk are in the addition of more histograms. However, running with 16 threads on the first file of run 3180 did not have any issues. See histograms in the log Entry https://logbooks.jlab.org/entry/3377698

**Comment by sparksn** [comment]
TRIG_online was not releasing the lock before returning early for non-physics events.
Elton's https://github.com/JeffersonLab/sim-recon/commit/a93b3c30a92ca49910d15cfb7f7c47fec4a63c00 commit fixes this problem.

**Comment by sparksn** [comment]
The `CDC_expert` problem is actually unrelated to recent changes in this plugin or the libraries that it uses. It was discovered that this crash only occurs when the run number changes within a single job; Typical usage is one run number per job, which is why it was not encountered before. 

 `CDC expert` defines histograms within a directory tree in the brun() method, which is called each time the run number changes; The crash occurs on the second call of brun(). @nsjarvis should consider moving the histogram definitions back to init(); This would still allow for a run-dependent histogram binning scheme to be employed within brun() (using SetBins()).

The funny thing is that this issue was discovered by, in fact, processing a single run.
The catch is that the input filename had been changed from the standard one, and EPICS events fallback to using the run number extracted from the filename. @faustus123 is working on improving this behavior.

For single-run processing, the crash disappeared after changing the name of the input file to the standard one.

**Comment by nsjarvis** [comment]
Will do.  Thanks, Nathan.

**Comment by sdobbs** [comment]
Are both these problems fixed?

**Comment by faustus123** [comment]
I think this may have been fixed with a commit I made last Wed. There were histograms that were only being made if the run number was > 3675, but they were being filled regardless. I'm not sure if this completely explains the crashes Nathan saw, but at least it stopped crashing on me for the use case I was testing. I'm going to close this and we can re-open it if the problem presents again.

**Comment by nsjarvis** [comment]
I was hoping that too, but it still crashes on file snippets when the run number is 0.  (I don’t know that that’s the cause, I took a quick look last night and found it is fine with 3180 but segfaults with a snippet from the start of 3180).     

Is there a better way to find out which version of fa125 firmware was in use?    Is there anything in the file snippet (evio_cull_events) that can be seen from init or brun that this could be derived from?   It’s obvious when the events are read in but the histograms need to be set up first.    

If not, then I’ll move the highly version-dependent histograms into a separate plugin which isn’t used in the routine monitoring.

**Comment by sparksn** [comment]
CDC_expert still crashes in brun() when the run number changes.

**Comment by nsjarvis** [comment]
CDC_expert is causing far too much trouble.   It was a headache modifying it to work with both firmware versions and it was never intended to be used over 2+ different runs (in case someone picks the 2 runs where the firmware changes).

Please just delete it.    I will make something else for use with the new firmware only.  

Thank you.

Naomi.

**Comment by faustus123** [comment]
Too late. This showed a problem that will definitely come up again so we HAVE to figure it out and fix it. (Which I think I just did.)

The problem was that it was not only replacing the histograms when brun was called a second time, it also tried replacing the CDC_expert TDirectory. I saw it crash on the following line when the run number changed:

gDirectory->mkdir("CDC_expert")->cd();

I'm pretty sure this was due to the mkdir() method returning NULL since the directory already existed.
An additional consideration is that I don't think it was good to have the histograms recreated since that effectively zeroed them, losing any data that came before the time brun was called. I put in a flag to ensure the body of brun() is executed only once and the program did not crash.

If should be emphasized that most plugins create the histograms (and TDirectory objects) in init() which is called only once. This plugin was special in that it required knowledge of the run number before creating the histograms, forcing that to wait until brun. Similar situation in the future will need a similar solution.
